Unified logging

diff --git a/scripts/postuninst b/scripts/postuninst
--- a/scripts/postuninst
+++ b/scripts/postuninst
@@ -1,46 +1,64 @@
 #!/bin/bash
-bDebug=0  # 0: delete log files, 1: preserve log files
-LOG="/var/tmp/$SYNOPKG_PKGNAME.log"
-DTFMT="+%Y-%m-%d %H:%M:%S"
-# SCRIPTPATHTHIS="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )" # /var/packages/autorun/scripts/
+SCRIPTPATHscripts="$( cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; /bin/pwd -P )"
+scriptpathParent=${SCRIPTPATHscripts%/*}
+if [[ -f "$scriptpathParent/WIZARD_UIFILES/log_hlp.sh" ]]; then
+  # shellcheck source=..\WIZARD_UIFILES\log_hlp.sh
+  source "$scriptpathParent/WIZARD_UIFILES/log_hlp.sh"
+  # logInfo 8 "postuninst: logInfo / logError available!"
+else
+  LOG="/var/tmp/$SYNOPKG_PKGNAME.log" # possibly no permission
+  DTFMT="+%Y-%m-%d %H:%M:%S"
+  echo "$(date "$DTFMT"): postuninst: '$scriptpathParent/WIZARD_UIFILES/log_hlp.sh' not available!" >> "$LOG"
+fi
 user=$(whoami)
-echo "$(date "$DTFMT"): postuninst V$SYNOPKG_PKGVER started as $user...<br/>" >> "$LOG"
-# echo "$(date "$DTFMT"): p0='$0'" >> "$LOG" # $app_name is empty!!
+logInfo 6 "postuninst V$SYNOPKG_PKGVER started as $user..."
+# echo "$(date "$DTFMT"): p0='${BASH_SOURCE[0]}'" >> "$LOG" # $app_name is empty!!
 configFilePathName="${SYNOPKG_PKGVAR}/config"  # $SYNOPKG_PKGVAR is /volume1/@appdata/autorun and is o.k., still available
 # echo "$(date "$DTFMT"): configFilePathName='$configFilePathName'" >> "$LOG"
 # after uninstall is /var/packages/$SYNOPKG_PKGNAME no more available, only /volume1/@appdata/autorun !!!
 # Attention: If a new version is installed, then this file from the old version
 #   is executed before the preinst of the new version!
-if [[ "${pkgwizard_remove_settings}" == "true" ]] || [[ "${pkgwizard_remove_settings}" == "false" ]]; then
+msgui="V$SYNOPKG_PKGVER, post-uninstall "
+# shellcheck disable=2154
+if [[ "${config_remove_settings}" == "true" ]] || [[ "${config_remove_settings}" == "false" ]]; then
 	# WIZZARD_UIFILES/uninstall_uifile_<lng> was done before! So it's a real uninstall, not an upgrade!
-  if [[ "$bDebug" -eq "0" ]]; then
-    rm "$LOG"
-    rm "/var/tmp/resource.$SYNOPKG_PKGNAME.*"
-    rm "/var/log/packages/$SYNOPKG_PKGNAME.log"
-    rm "/var/log/packages/$SYNOPKG_PKGNAME.log.*.xz"
-    rm "${SYNOPKG_PKGVAR}/execLog"
-    # echo "$(date "$DTFMT"): Old logfiles removed" >> "$LOG"
-  else
-    echo "$(date "$DTFMT"): Logfiles preserved due to bDebug!=0" >> "$LOG"
-  fi
-fi
-if [[ "${pkgwizard_remove_settings}" == "true" ]]; then
-  res=$(rm -r --interactive=never "${SYNOPKG_PKGVAR}") # remove folder
-  ret=$?
-  # if [[ "$bDebug" -ne "0" ]]; then
-    echo "$(date "$DTFMT"): Result from 'rm -r \"${SYNOPKG_PKGVAR}\"': $ret, '$res'" >> "$LOG"
-  # fi
-else
-  if [[ -f "${SYNOPKG_PKGVAR}\config" ]]; then
-    # put old version to config file, so that postinst can check whether its an upgrade or only settings change
-    res=$(grep "VERSION=" "${SYNOPKG_PKGVAR}\config")
-    if [[ -n "$res" ]]; then
-      res="$(sed -i "s|^VERSION=.*$|VERSION=\"${SYNOPKG_PKGVAR}\"|" "${SYNOPKG_PKGVAR}\config")"
+  if [[ "$config_remove_log" == "true" ]]; then
+    res1=$( { rm "$LOG";} 2>&1 )
+    ret1=$?
+    msg="'rm $LOG': $ret1 ($res1)"
+    res2="$( { rm "/var/tmp/resource.$SYNOPKG_PKGNAME.log";} 2>&1 )"
+    ret2=$?
+    msg="$msg, 'rm /var/tmp/resource.$SYNOPKG_PKGNAME.log': $ret2 ($res2)"
+    res3="$( { rm "/var/log/packages/$SYNOPKG_PKGNAME.*";} 2>&1 )"
+    ret3=$?
+    msg="$msg, 'rm /var/tmp/resource.$SYNOPKG_PKGNAME.*': $ret3 ($res3)"
+    res4="$( { rm "/var/log/packages/$SYNOPKG_PKGNAME.log.*.xz";} 2>&1 )"
+    ret4=$?
+    msg="$msg, 'rm /var/log/resource.$SYNOPKG_PKGNAME.*': $ret4 ($res4)"
+    res5=$( { rm "${SYNOPKG_PKGVAR}/execLog";} 2>&1 )
+    ret5=$?
+    msg="$msg, 'rm ${SYNOPKG_PKGVAR}/execLog': $ret5 ($res5)"
+    if [[ "$ret1" -ne "0" ]] || [[ "$ret5" -ne "0" ]]; then
+      msgui="$msgui, removing old logfiles failed: ret1='$ret1', res1='$res1', ret2='$ret2', res2='$res2', ret3='$ret3', res3='$res3', ret4='$ret4', res4='$res4', ret5='$ret5', res5='$res5'"
     else
-      echo "VERSION=\"${SYNOPKG_PKGVAR}\"" >> "${SYNOPKG_PKGVAR}\config"
+      msgui="$msgui, logfiles successfully removed"
     fi
+  else
+    msgui="$msgui, logfiles preserved on uninstall due wizard selection!"
   fi
+  if [[ "${config_remove_settings}" == "true" ]]; then
+    # Problem: after an uninstallation with "${config_remove_settings}" == "true" this value is still set at next installation!!!!!
+    res=$( { rm -r --interactive=never "${SYNOPKG_PKGVAR}"; } 2>&1 ) # remove folder
+    ret=$?
+    if [[ "$ret" -ne "0" ]]; then
+      msgui="$msgui, removing settings failed! Result from 'rm -r --interactive=never \"${SYNOPKG_PKGVAR}\"': $ret, '$res'"
+    fi
+  else
+    msgui="$msgui, settings preserved on uninstall due wizard selection!"
+  fi
+  logInfo 4 "$msgui, postuninst done"
+  exit 0
 fi
-echo "$(date "$DTFMT"): ... postuninst done<br/>" >> "$LOG"
+logInfo 4 "... postuninst done"
 exit 0
 
diff --git a/scripts/preinst b/scripts/preinst
--- a/scripts/preinst
+++ b/scripts/preinst
@@ -1,57 +1,74 @@
 #!/bin/bash
-LOG="/var/tmp/$SYNOPKG_PKGNAME.log" # /var/log/tmp is a link to /var/tmp !!
-DTFMT="+%Y-%m-%d %H:%M:%S"
-SCRIPTPATHTHIS="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 # preinst starts from an temporary folder like /volume1/@tmp/synopkg/install.XDdQUB/scripts/preinst
+SCRIPTPATHscripts="$( cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; /bin/pwd -P )"
 user=$(whoami) # EnvVar $USER may be not well set, user is '<appName>'
-echo "$(date "$DTFMT"): preinst $0 V$SYNOPKG_PKGVER (physical path SCRIPTPATHTHIS: $SCRIPTPATHTHIS, user=$user, UID=$(id -u "$user"))... <br/>" >> "$LOG"
+msg="preinst ${BASH_SOURCE[0]} V$SYNOPKG_PKGVER (physical path SCRIPTPATHscripts: $SCRIPTPATHscripts, user=$user, UID=$(id -u "$user"))... "
 # SHELL='/sbin/nologin', $SHELL: causes "No such file or directory error" in /var/log/bash_err.log!
 # versShell="$($SHELL --version | sed -n '1p')" # Environment variable SHELL may be 'ash', but /bin/ash may be a link to bash
 # this may be somthing like "GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)"
 # echo "$(date "$DTFMT"): Shell: SHELL='$SHELL' ($versShell)" >> "$LOG"
 
-# user is equal to $SYNOPKG_PKGNAME, SCRIPTPATHTHIS is e.g. /volume1/@tmp/synopkg/install.HbEips/scripts/
+# user is equal to $SYNOPKG_PKGNAME, SCRIPTPATHscripts is e.g. /volume1/@tmp/synopkg/install.HbEips/scripts/
 # ${SYNOPKG_TEMP_UPGRADE_FOLDER} # e.g. /volume1/@tmp/synopkg.tmp, empty
-scriptpathParent=${SCRIPTPATHTHIS%/*}
-# echo "$(date "$DTFMT"): ls -l $scriptpathParent: $(ls -l "$scriptpathParent")" >> "$LOG"
-osMin=$(/bin/get_key_value "$scriptpathParent/INFO" "os_min_ver")  # os_min_ver="7.0-40000"
-echo "$(date "$DTFMT"): From INFO file: os_min_ver='$osMin' via get_key_value" >> "$LOG"
-
-osMinMajor="${osMin%%.*}"
-osMinBuild="${osMin#*-}"
-osMinMinor="${osMin#*.}"
-osMinMinor="${osMinMinor%-*}"
-# productversion="7.1.1", majorversion="7", minorversion="1", major="7", minor="1", micro="1", buildnumber="42962"
-# DSMMAJOR=$(/bin/get_key_value /etc.defaults/VERSION majorversion)
-dsmMajor=$(/bin/get_key_value /etc.defaults/VERSION majorversion)
-dsmMinor=$(/bin/get_key_value /etc.defaults/VERSION minorversion)
-dsmBuild=$(/bin/get_key_value /etc.defaults/VERSION buildnumber)
-# if [ "$DSMMAJOR" -lt 7 ]; then
-vers=0 # not ok
-if [[ "$dsmMajor" -gt "$osMinMajor" ]]; then
-  vers=1
-elif [[ "$dsmMajor" -eq "$osMinMajor" ]]; then
-  if [[ "$dsmMinor" -gt "$osMinMinor" ]]; then
-    vers=1  
-  elif [[ "$dsmMinor" -eq "$osMinMinor" ]]; then
-    if [[ "$dsmBuild" -ge "$osMinBuild" ]]; then
-      vers=1  
-    fi
-  fi  
+scriptpathParent=${SCRIPTPATHscripts%/*}
+if [[ -f "$scriptpathParent/WIZARD_UIFILES/log_hlp.sh" ]]; then
+  # shellcheck source=..\WIZARD_UIFILES\log_hlp.sh
+  source "$scriptpathParent/WIZARD_UIFILES/log_hlp.sh"
+  logInfo 6 "$msg, preinst: logInfo / logError available! user=$(whoami)"
+  # is account $SYNOPKG_PKGNAME already available?
+else
+  LOG="/var/tmp/$SYNOPKG_PKGNAME.log" # possibly no permission
+  DTFMT="+%Y-%m-%d %H:%M:%S"
+  echo "$(date "$DTFMT"): preinst: '$scriptpathParent/WIZARD_UIFILES/log_hlp.sh' not available!" >> "$LOG"
 fi
-if [[ "$vers" -ne "1" ]]; then
-  lngUser="$SYNOPKG_DSM_LANGUAGE"
-  # echo "$(date "$DTFMT"): lngUser=SYNOPKG_DSM_LANGUAGE='$lngUser'" >> "$LOG"
-	# package.tgz and also the extracted package are available!
-	if [[ -f "$scriptpathParent/package/ui/texts/$lngUser/lang.txt" ]]; then
-    # preinstDsmVersError=$(/bin/get_key_value "$scriptpathParent/package/ui/texts/$lngUser/lang.txt" "preinstDsmVersError")  # "... ${osMin} ..." is not yet expanded
-		eval "$(grep "preinstDsmVersError=" "$scriptpathParent/package/ui/texts/$lngUser/lang.txt")" # "... ${osMin} ..." is expanded
-		echo "$preinstDsmVersError" > "$SYNOPKG_TEMP_LOGFILE"      
-	else
-    echo "This package version can only be used in DSM $osMin and above! Earlier package versions may be possible on your DSM version, see <a target='_blank' rel='noopener noreferrer' href='https://github.com/reidemei/synology-autorun#install'>https://github.com/reidemei/synology-autorun#install</a>" > "$SYNOPKG_TEMP_LOGFILE"
-	fi	
-	exit 1
+if grep -q "^${SYNOPKG_PKGNAME}:" "/etc/passwd"; then
+  logUser=$(stat -c '%U' "$LOG")
+  logGrp=$(stat -c '%G' "$LOG")
+  logInfo 6 "The account '${SYNOPKG_PKGNAME}' exists already, user and group of $LOG: $logUser:$logGrp"
+  if [[ "$(whoami)" == "root" ]] && [[ "$logUser" != "${SYNOPKG_PKGNAME}" ]]; then
+    chown "$SYNOPKG_PKGNAME":"$SYNOPKG_PKGNAME" "$LOG" 
+    logInfo 6 "chown $SYNOPKG_PKGNAME:$SYNOPKG_PKGNAME $LOG done!"
+  fi
 fi
-echo "$(date "$DTFMT"): ... DSM OS version checked (${dsmMajor}.${dsmMinor}-${dsmBuild} >= ${osMin}), preinst finished<br/>" >> "$LOG"
+# Checking osMin is done by Synology Installation Wizzard, therfore deactivated here
+# osMin=$(/bin/get_key_value "$scriptpathParent/INFO" "os_min_ver")  # os_min_ver="7.0-40000"
+# osMinMajor="${osMin%%.*}"
+# osMinBuild="${osMin#*-}"
+# osMinMinor="${osMin#*.}"
+# osMinMinor="${osMinMinor%-*}"
+# # productversion="7.1.1", majorversion="7", minorversion="1", major="7", minor="1", micro="1", buildnumber="42962"
+# # DSMMAJOR=$(/bin/get_key_value /etc.defaults/VERSION majorversion)
+# dsmMajor=$(/bin/get_key_value /etc.defaults/VERSION majorversion)
+# dsmMinor=$(/bin/get_key_value /etc.defaults/VERSION minorversion)
+# dsmBuild=$(/bin/get_key_value /etc.defaults/VERSION buildnumber)
+# # if [ "$DSMMAJOR" -lt 7 ]; then
+# vers=0 # not ok
+# if [[ "$dsmMajor" -gt "$osMinMajor" ]]; then
+#   vers=1
+# elif [[ "$dsmMajor" -eq "$osMinMajor" ]]; then
+#   if [[ "$dsmMinor" -gt "$osMinMinor" ]]; then
+#     vers=1  
+#   elif [[ "$dsmMinor" -eq "$osMinMinor" ]]; then
+#     if [[ "$dsmBuild" -ge "$osMinBuild" ]]; then
+#       vers=1  
+#     fi
+#   fi  
+# fi
+# if [[ "$vers" -ne "1" ]]; then
+#   lngUser="$SYNOPKG_DSM_LANGUAGE"
+#   # package.tgz and also the extracted package are available!
+#   logError "Actual DSM Version ${dsmMajor}.${dsmMinor}-${dsmBuild} is less than required ${osMin}, specified in INFO file!"
+#   if [[ -f "$scriptpathParent/package/ui/texts/$lngUser/lang.txt" ]]; then
+#     # preinstDsmVersError=$(/bin/get_key_value "$scriptpathParent/package/ui/texts/$lngUser/lang.txt" "preinstDsmVersError")  # "... ${osMin} ..." is not yet expanded
+#     eval "$(grep "preinstDsmVersError=" "$scriptpathParent/package/ui/texts/$lngUser/lang.txt")" # "... ${osMin} ..." is expanded
+#     #shellcheck disable=2154
+#     echo "$preinstDsmVersError" > "$SYNOPKG_TEMP_LOGFILE"
+#   else
+#     echo "This package version can only be used in DSM $osMin and above! Earlier package versions may be possible on your DSM version, see <a target='_blank' rel='noopener noreferrer' href='https://github.com/reidemei/synology-autorun#install'>https://github.com/reidemei/synology-autorun#install</a>" > "$SYNOPKG_TEMP_LOGFILE"
+#   fi
+#   exit 1
+# fi
+# logInfo 6 "... DSM OS version checked (actual ${dsmMajor}.${dsmMinor}-${dsmBuild} >= ${osMin} from INFO file), preinst finished"
+logInfo 6 "preinst finished"
 exit 0
 
