Fixes, new features and code cleanup
The script, which should be executed at storage connect can now be located either on the external storage or inside of DSM.

diff --git a/scripts/start-stop-status b/scripts/start-stop-status
--- a/scripts/start-stop-status
+++ b/scripts/start-stop-status
@@ -1,20 +1,21 @@
 #!/bin/bash
+# This start-stop-status is called about once per second!
 user=$(whoami) # EnvVar $USER may be not well set
 # user = "root" if the sudo cp /var/packages/$SYNOPKG_PKGNAME/conf/privilege.root /var/packages/$SYNOPKG_PKGNAME/conf/privilege
 # user = "$SYNOPKG_PKGNAME" = '<appName>' if the copy was not done
 LOG="/var/log/tmp/$SYNOPKG_PKGNAME.log"
 DTFMT="+%Y-%m-%d %H:%M:%S"
-SCRIPTPATHTHIS="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; /bin/pwd -P )"
-configFilePathName="/var/packages/$SYNOPKG_PKGNAME/var/config"
-source "/var/packages/$SYNOPKG_PKGNAME/target/common" # set lngUser, lngDsm
+SCRIPTPATHTHIS="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; /bin/pwd -P )" # /var/packages/autorun/scripts !!
   
 case $1 in
   prestart)
     echo "$(date "$DTFMT"): PRESTART of start-stop-status script V$SYNOPKG_PKGVER '$1' as user '$user'<br/>" >> "$LOG"
-    #### is not occuring !!!????
+    #### is occuring if ...!
     ;;
   start)
-    echo "$(date "$DTFMT"): start-stop-status script V$SYNOPKG_PKGVER '$1' as user '$user'. SYNOPKG_DSM_LANGUAGE='$lngDsm'<br/>" >> "$LOG"
+    configFilePathName="/var/packages/$SYNOPKG_PKGNAME/var/config"
+    source "/var/packages/$SYNOPKG_PKGNAME/target/common" start-stop-status # set lngUser, lngUser
+    echo "$(date "$DTFMT"): start-stop-status script V$SYNOPKG_PKGVER '$1' as user '$user'. SYNOPKG_DSM_LANGUAGE='$lngUser'<br/>" >> "$LOG"
     if [ "$user" != "root" ]; then
       echo "$(date "$DTFMT"): start-stop-status '$1' as user '$user' != \"root\". <br/>" >> "$LOG"      
       eval $(grep -s "copyPriviledge=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
@@ -23,54 +24,80 @@ case $1 in
       else
         echo "The copy command 'cp /var/packages/$SYNOPKG_PKGNAME/conf/privilege.root /var/packages/$SYNOPKG_PKGNAME/conf/privilege' was not yet executed. Therefore the package '$SYNOPKG_PKGNAME' cannot be started" > "$SYNOPKG_TEMP_LOGFILE"
       fi
-      # exit 3 # this would run into repair loop and no exit possible except uninstall
+      # exit 3 # this would run into repair loop and no exit possible except uninstall/re-install
     else # root
-      # enable log deleting for ui/showlog.cgi:
+      error=0
+			# enable log deleting for ui/showlog.cgi:
       chmod 664 "$LOG"
-      chown $SYNOPKG_PKGNAME:$SYNOPKG_PKGNAME "$LOG"
+      chown "$SYNOPKG_PKGNAME":"$SYNOPKG_PKGNAME" "$LOG"
       if [[ ! -L "/var/packages/$SYNOPKG_PKGNAME/var/detailLog" ]]; then
         ln -s "$LOG" "/var/packages/$SYNOPKG_PKGNAME/var/detailLog" # for access from cgi file
       fi
       chmod 644 "/var/packages/$SYNOPKG_PKGNAME/var/detailLog"
-      chown $SYNOPKG_PKGNAME:$SYNOPKG_PKGNAME "/var/packages/$SYNOPKG_PKGNAME/var/detailLog"
-      scriptAfterEject=$(grep "^SCRIPT_AFTER_EJECT=" "$configFilePathName")
-      scriptAfterEject=${scriptAfterEject#SCRIPT_AFTER_EJECT=\"}
-      scriptAfterEject=${scriptAfterEject%\"}
-      if [[ -n "$scriptAfterEject" ]]; then # script setup
-        echo "$(date "$DTFMT"): start-stop-status: Script after eject '$scriptAfterEject'<br/>" >> "$LOG"            
-        if [[ ! -f "$scriptAfterEject" ]]; then
-          eval $(grep -s "scriptAfterNA=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
-          echo "$scriptAfterNA" > "$SYNOPKG_TEMP_LOGFILE"
-          echo "$(date "$DTFMT"): Error: The 'Script after' file $SCRIPT_AFTER_EJECT is not available!" >> "$LOG"
-        elif [[ ! -x "$scriptAfterEject" ]]; then     
-          eval $(grep -s "scriptAfterNexec=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
-          echo "$scriptAfterNexec" > "$SYNOPKG_TEMP_LOGFILE"
-          echo "$(date "$DTFMT"): Error: The 'Script after' file $SCRIPT_AFTER_EJECT is not executable!" >> "$LOG"
+      chown "$SYNOPKG_PKGNAME":"$SYNOPKG_PKGNAME" "/var/packages/$SYNOPKG_PKGNAME/var/detailLog"
+      eval "$(grep "^SCRIPT=" "$configFilePathName")"
+      files=""
+      if [[ "$SCRIPT" == *"/"* ]]; then
+        files="$SCRIPT"  # The script to execute at storage connect is on the DSM, so we can check it
+      fi
+      eval "$(grep "^SCRIPT_AFTER_EJECT=" "$configFilePathName")"
+      if [[ -n "$SCRIPT_AFTER_EJECT" ]]; then # script is setup, check it!
+        files="$files $SCRIPT_AFTER_EJECT"
+        #echo "$(date "$DTFMT"): start-stop-status: Script after eject '$SCRIPT_AFTER_EJECT'<br/>" >> "$LOG"
+      #else # if [[ -n "$SCRIPT_AFTER_EJECT" ]]
+        #echo "$(date "$DTFMT"): start-stop-status: No script after eject<br/>" >> "$LOG"
+      fi # if [[ -n "$SCRIPT_AFTER_EJECT" ]]
+      for f in $files; do # check scripts
+        if [[ ! -f "$f" ]]; then
+          eval $(grep -s "scriptNA=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
+          echo "$scriptNA" > "$SYNOPKG_TEMP_LOGFILE"
+          echo "$(date "$DTFMT"): Error: The script file '$f' is not available!" >> "$LOG"
+          res=$(findFileIgnoreCase $f)
+          result=$?
+          #echo "$(date "$DTFMT"): findFileIgnoreCase result: $result, '$res'" >> "$LOG"
+          if [[ "$result" -eq "1" ]]; then # with "ignore case script found!"
+            eval $(grep -s "scriptNAcase=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
+            echo "$(date "$DTFMT"): Suspicious: '$f' with different upper/lower case found: '$res'. It will not be executed!!" >> "$LOG"
+            echo "  $scriptNAcase" >> "$SYNOPKG_TEMP_LOGFILE"
+          fi
+          eval $(grep -s "setupCorrection=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
+          echo " $setupCorrection" >> "$SYNOPKG_TEMP_LOGFILE"
+          # exit 2 # this would run into repair loop and no exit possible except uninstall/re-install
+					error=1
+        elif [[ ! -x "$f" ]]; then     
+          eval $(grep -s "scriptNexec=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
+          echo "$scriptNexec" > "$SYNOPKG_TEMP_LOGFILE"
+          echo "$(date "$DTFMT"): Error: The script file $f is not executable!" >> "$LOG"
+          # exit 2 # this would run into repair loop and no exit possible except uninstall/re-install
+					error=1
         else
-          scriptName="$scriptAfterEject"
-          res=$(file -b "$scriptName")
+          res=$(file -b "$f")
           ret=$?
-          echo "$(date "$DTFMT"): File coding check '$scriptName' result $ret: $res" >> "$LOG"
+          echo "$(date "$DTFMT"): File coding check '$f' result $ret: $res" >> "$LOG"
           if [[ $res == *"CRLF line terminators"* ]]; then
-            echo "  File coding check '$scriptName' result $ret: $res"
+            echo "  File coding check '$f' result $ret: $res"
             echo "  ######## Windows line terminator need to be converted to Unix! #########"
             eval $(grep -s "wrongLineBreakWin=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
             echo "$wrongLineBreakWin" > "$SYNOPKG_TEMP_LOGFILE"
+            # exit 2 # this would run into repair loop and no exit possible except uninstall/re-install
+  					error=1
           elif [[ $res == *"with CR line terminators"* ]]; then
-            echo "  File coding check '$scriptName' result $ret: $res"
+            echo "  File coding check '$f' result $ret: $res"
             echo "  ######## MAC line terminator need to be converted to Unix! #########"
             eval $(grep -s "wrongLineBreakMac=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
             echo "$wrongLineBreakMac" > "$SYNOPKG_TEMP_LOGFILE"
+            # exit 2 # this would run into repair loop and no exit possible except uninstall/re-install
+  					error=1
           elif [[ "$res" == *"ISO-8859 text"* ]]; then 
-            echo "  File coding check '$scriptName' result $ret: $res"
+            echo "  File coding check '$f' result $ret: $res"
             echo "  ######## Please convert to UTF-8! ##########"
             eval $(grep -s "wrongCodePage=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
             echo "$wrongCodePage" > "$SYNOPKG_TEMP_LOGFILE"
+            #exit 2
+  					error=1						
           fi # CRLF       
-        fi
-      else # if [[ -n "$scriptAfterEject" ]]
-        echo "$(date "$DTFMT"): start-stop-status: No script after eject<br/>" >> "$LOG"            
-      fi # if [[ -n "$scriptAfterEject" ]]
+        fi # existing and executable
+      done
 
       # check whether the entered user/usergroup for desktop notification is valid:
       notyfyUsers=$(grep "^NOTIFY_USERS=" "$configFilePathName")
@@ -84,7 +111,7 @@ case $1 in
             echo "$(date "$DTFMT"): The group account '$notyfyUsers' for desktop message does not exist! Wrong entry replaced by '@users'" >> "$LOG"
             eval $(grep -s "notifyGroupError=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
             echo "$notifyGroupError" > "$SYNOPKG_TEMP_LOGFILE"
-            sed -i 's/^NOTIFY_USERS=*$/^NOTIFY_USERS=@users/' "$configFilePathName"      
+            sed -i 's/^NOTIFY_USERS=.*$/^NOTIFY_USERS=@users/' "$configFilePathName"
           fi
         else # single user
           # userExist=$(grep -o "^${notyfyUsers}:" /etc/passwd) # long list of accounts!
@@ -94,7 +121,7 @@ case $1 in
             echo "$(date "$DTFMT"): The user account '$notyfyUsers' for desktop messages does not exist! Therefore the wrong entry replaced by '@users'. Run Installation again to enter another value!" >> "$LOG"
             eval $(grep -s "notifyUserError=" "/var/packages/$SYNOPKG_PKGNAME/target/ui/texts/$lngUser/lang.txt")
             echo "$notifyUserError" > "$SYNOPKG_TEMP_LOGFILE"
-            sed -i 's/^NOTIFY_USERS=*$/^NOTIFY_USERS=@users/' "$configFilePathName"      
+            sed -i 's/^NOTIFY_USERS=.*$/^NOTIFY_USERS=@users/' "$configFilePathName"
           fi # not existing user
         fi # if goupe else user
       fi            
@@ -103,23 +130,28 @@ case $1 in
       echo "$(date "$DTFMT"): start executed, but app was already running<br/>" >> "$LOG"    
       exit 1
     else
-      echo "$(date "$DTFMT"): start-stop-status script 'start', SYNOPKG_PKGDEST='$SYNOPKG_PKGDEST'<br/>" >> "$LOG"
-      resultStart=$(cp "/var/packages/$SYNOPKG_PKGNAME/target/rules" "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules")
-      retvalStart=$?
-      echo "$(date "$DTFMT"): cp 99-$SYNOPKG_PKGNAME.rules to '/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules': retval=$retvalStart, result='$resultStart'<br/>" >> "$LOG"      
-      chmod 644 "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules"
-      # chown root:root "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules" # required? 
-      /usr/bin/udevadm control --reload-rules
-      if [ -f "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules" ];  then
-			  echo "$(date "$DTFMT"): $SYNOPKG_PKGNAME was STARTED!" >> "$SCRIPT_EXEC_LOG"
-			fi	
+      if [[ "$error" -eq "0" ]]; then
+
+        echo "$(date "$DTFMT"): start-stop-status script 'start', SYNOPKG_PKGDEST='$SYNOPKG_PKGDEST'<br/>" >> "$LOG"
+        resultStart=$(cp "/var/packages/$SYNOPKG_PKGNAME/target/rules" "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules")
+        retvalStart=$?
+        echo "$(date "$DTFMT"): cp 99-$SYNOPKG_PKGNAME.rules to '/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules': retval=$retvalStart, result='$resultStart'<br/>" >> "$LOG"      
+        chmod 644 "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules"
+        # chown root:root "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules" # required? 
+        /usr/bin/udevadm control --reload-rules
+        if [ -f "/usr/lib/udev/rules.d/99-$SYNOPKG_PKGNAME.rules" ];  then
+			    echo "$(date "$DTFMT"): Package '$SYNOPKG_PKGNAME' was STARTED!" >> "$SCRIPT_EXEC_LOG"
+          echo "$(date "$DTFMT"): ... start via start-stop-status script successfully finished<br/>" >> "$LOG"
+			  fi	
+      else
+        echo "$(date "$DTFMT"): start-stop-status script 'start' failed!<br/>" >> "$LOG"
+			fi
     fi
-    echo "$(date "$DTFMT"): ... start via start-stop-status script successfully finished<br/>" >> "$LOG"
     exit 0
   ;;
   prestop)  # can be disabled via precheckstartstop in INFO file
     #### is not occuring !!!????
-    echo "$(date "$DTFMT"): start-stop-status script V$SYNOPKG_PKGVER '$1' as user '$user'<br/>" >> "$LOG"
+    echo "$(date "$DTFMT"): PRESTOP start-stop-status script V$SYNOPKG_PKGVER '$1' as user '$user'<br/>" >> "$LOG"
   ;;
   stop)
     echo "$(date "$DTFMT"): start-stop-status script V$SYNOPKG_PKGVER '$1' as user '$user'<br/>" >> "$LOG"
@@ -128,7 +160,7 @@ case $1 in
       retvalStop=$?
       echo "$(date "$DTFMT"): rm 99-$SYNOPKG_PKGNAME.rules retval=$retvalStop, result='$resultStop'<br/>" >> "$LOG"
       /usr/bin/udevadm control --reload-rules
-      echo "$(date "$DTFMT"): $SYNOPKG_PKGNAME was STOPPED!" >> "$SCRIPT_EXEC_LOG"
+      echo "$(date "$DTFMT"): Package '$SYNOPKG_PKGNAME' was STOPPED!" >> "$SCRIPT_EXEC_LOG"
     else
       echo "$(date "$DTFMT"): stop executed, but app was not running<br/>" >> "$LOG"    
     fi
